services:
  valkey-cluster:
    image: pvogel/valkey-cluster
    ports:
        - 14000-14005:14000-14005/tcp
    environment:
        IP: ${VALKEY_CLUSTER_IP}
        SENTINEL: ${VALKEY_USE_SENTINEL}
        STANDALONE: ${VALKEY_USE_STANDALONE}
        INITIAL_PORT: 14000
        MASTERS: 3
        SLAVES_PER_MASTER: 1
