name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 8.1.1
          - 8.0.3
          - 7.2.9
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build the latest Docker image
        run: |
          export VERSION=${{ matrix.version }}
          export CR_PAT=${{ secrets.CR_PAT }}
          envsubst < Dockerfile.tmpl > Dockerfile
          echo $CR_PAT | docker login ghcr.io -u mix3 --password-stdin
          docker buildx create --use
          docker buildx build --attest type=provenance,mode=max --platform linux/amd64,linux/arm64 --push -t mix3/valkey-cluster:$VERSION .
