name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the latest Docker image
        run: |
            TAG=$(git rev-parse --short HEAD)
            docker login -u pvogel -p ${{ secrets.DOCKER_PASSWORD }} 
            docker buildx create --name mp-builder
            docker buildx use mp-builder
            docker buildx inspect --bootstrap
            docker buildx build --attest type=provenance,mode=max --platform linux/amd64,linux/arm64 --push -t pvogel/valkey-cluster:8.0.3-${TAG} -t pvogel/valkey-cluster:latest .
