name: Docker Image CI

on:
  push:
    branches:
      - main
env:
  REGISTRY_IMAGE: ${{ vars.DOCKERHUB_USER }}/valkery-cluster

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 8.1.1
          - 8.0.3
          - 7.2.9
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      - name: Log into registry Dockerhub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          export VERSION=${{ matrix.version }}
          envsubst < Dockerfile.tmpl > Dockerfile
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY_IMAGE }}:${{ matrix.version }}
          push: true
